### ISSUE TITLE
Doesn't work in Docker

### ISSUE THREAD

**Issue by hwittenborn** [ruanformigoni/flatimage#11]
When attempting to run the `arch.tar.gz` image in a Docker container (`ubuntu:latest`), I get an error about `resize2fs` not being found:

```sh
root@2269f44a3f54:~# ./arch.fim fim-resize 8G
cp: cannot stat '/tmp/fim/instance/caf5acd_20230919223918/mount/FmieLM/fim/static/resize2fs': No such file or directory
```

I'm not positive is FlatImage is supposed to support Docker (I know AppImage doesn't out of the box), but this felt like a bug to me since it just wasn't able to find the `resize2fs` binary.

**Comment by ruanformigoni** [comment]
I think it could work inside docker, but only with superuser privileges. I'll try it out and also take a look on why this executable is missing. Thanks for this finding.

**Comment by hwittenborn** [comment]
> I think it could work inside docker, but only with superuser privileges.

What's the reasoning behind that?

**Comment by ruanformigoni** [comment]
I've corrected my comment, I meant with the [privileged](https://github.com/containers/bubblewrap/issues/505) docker flag. I've made it work with:
```
docker run --privileged --device /dev/fuse --cap-add SYS_ADMIN -it --rm -v "$(pwd):/workdir" alpine:latest /bin/sh
```

Then I just entered the docker binding, `cd /workdir`, installed fuse with `apk add fuse` and executed the image with `./alpine.fim`.

**Comment by ruanformigoni** [comment]
Hi @hwittenborn , did you have a chance to check if this workaround fixed the issue for you? If so I'll include this as a note in README.md.

**Comment by hwittenborn** [comment]
Not yet @ruanformigoni, I got a bit busy with a few other things. I'll go ahead and do some testing real quick though.

**Comment by hwittenborn** [comment]
I can confirm that works, but it is a bit inconvenient to have to pass the `--privileged` flag to `docker` as it makes the Docker container able to access the host's environment.

Is `fuse3` pretty much a hard dependency for FlatImage? I know AppImages have the `--appimage-extract` option to use in Docker, but I'm not sure if there's an equivalent option that could be used in this program.

**Comment by ruanformigoni** [comment]
Thanks for confirming, it depends on the `fuse` device and the `fusermount` binary (which is provided by the fuse package), the later dependency may be possible to remove. Currently it does not support running in an 'extracted' filesystem, however it is doable.

**Comment by hwittenborn** [comment]
> Currently it does not support running in an 'extracted' filesystem, however it is doable.

 I think that approach would probably be the best. I wasn't sure if bubblewrap was requiring fuse (at which point I was thinking it'd be a hard dependency), but if it's just for stuff FlatImage directly uses I think it'd be better for it to just get extracted when running inside of Docker.

**Comment by ruanformigoni** [comment]
Updated `README.md` with an example in 80578e3.

**Comment by ruanformigoni** [comment]
An update on this, now the program will exit with something like:
```
Could not mount main filesystem '/workdir/arch.fim' to '/tmp/fim/instance/8a42a27_20231021215325/mount/NeClaj'
```
When the filesystem is not mounted correctly, instead of the `resize2fs not found` issue.
