### ISSUE TITLE
Move to GitHub as the primary repository?

### ISSUE THREAD

**Issue by hwittenborn** [ruanformigoni/flatimage#12]
I'm making a bit of a stretch here, but is there any chance you'd want to make the main code repository here on GitHub? I don't know how much you're into the GitLab ecosystem, but I'm interested in helping contribute to this project a bit and it'd be a fair bit easier on my part if I could do it all on here.

Stuff like https://github.com/ruanformigoni/flatimage/issues/10 could be solved pretty easily if everything was here on GitHub, because then the binaries could just be deployed from a GitHub Actions run (which I'm more than comfortable getting working). I also have a need for arm images of FlatImage, which I know how to do in GitHub Actions but not so much with GitLab CI.

I'm just throwing this out there to get some thoughts, let me know what you think!

**Comment by ruanformigoni** [comment]
Hi @hwittenborn and thanks for your feedback. I'll create a CI workflow here as well.

**Comment by ruanformigoni** [comment]
Hi @hwittenborn , I've moved the workflow here as the primary repository to work on the ARM support.
