### ISSUE TITLE
How to call a binary from the host system's `/usr/bin` folder?

### ISSUE THREAD

**Issue by hwittenborn** [ruanformigoni/flatimage#13]
I have a use case that involves calling `xdg-open` on a URL, which should open up the link in the user's default browser. I can't know what browser a user will be using in advance though, so I'd like to just call whatever browser the system's registered with.

There doesn't seem to be a way to access the available browsers from `/usr/bin` though, is there something I've overlooked or is there just not support for it yet?

I'm not quite sure how much work would be involved, but I'd be open to help working on the feature if need be.

**Comment by hwittenborn** [comment]
It looks like this is currently impossible due to `/usr` being hardcoded inside of the container:

https://github.com/ruanformigoni/flatimage/blob/caf5acd7607c491cc874a5bf04ea3674cb1bd8bd/src/scripts/_boot.sh#L337-L340

Perhaps there could be a user-defined config file saying what files/directories are mapped from the host (in addition to any sane defaults)?

**Comment by ruanformigoni** [comment]
Hi @hwittenborn , this should be possible with portals, as is pointed out by the link you have provided. I haven't looked into this functionality yet, but feel free to do so.
