### ISSUE TITLE
Make latest Ubuntu LTS the default deb-based image

### ISSUE THREAD

**Issue by hwittenborn** [ruanformigoni/flatimage#14]
I noticed that Ubuntu Focal is the currently latest example, but I think it'd make more sense to use Ubuntu Jammy considering it's the latest Ubuntu LTS.

Regarding that as well, I think it could be handy to include a command that allows publishing just one image, and then easily allowing swapping the APT repositories to use a different distro (i.e. any Debian/Ubuntu release). I was thinking this could be done by hot-swapping out the config in `/etc/apt/sources.list` and then just running an `apt-get update && apt get upgrade`.

I don't think there'd need to be more than two configs in that case - one for Debian-based and one for Ubuntu-based. Then the release's codename could just be swapped in the `sources.list` file.

What do you think?

**Comment by hwittenborn** [comment]
Should be solved by https://gitlab.com/formigoni/flatimage/-/merge_requests/1.

**Comment by ruanformigoni** [comment]
Thanks for the PR @hwittenborn :smile: , I'll check it out.

**Comment by ruanformigoni** [comment]
PR [merged](https://gitlab.com/formigoni/flatimage/-/merge_requests/1). Thanks!
