### ISSUE TITLE
Automatically push changes from GitLab to GitHub

### ISSUE THREAD

**Issue by hwittenborn** [ruanformigoni/flatimage#15]
Assuming #12 doesn't get implemented, it would be nice if the GitLab project's code could be automatically pushed over here to GitHub. It looked like it'd be pretty straightfoward to do, looking at https://docs.gitlab.com/ee/user/project/repository/mirror/push.html#set-up-a-push-mirror-from-gitlab-to-github.

**Comment by ruanformigoni** [comment]
Hello! #12 is finished, so I'll close this.
