### ISSUE TITLE
Magick missing, "No such file or directory"

### ISSUE THREAD

**Issue by fiftydinar** [ruanformigoni/flatimage#31]
I get this error on Arch & Alpine flatimage whenever I want to change something there (didn't try Ubuntu flatimage, but it possibly has the same error):

```
cp: cannot stat '/tmp/fim/app/266c699_20240428082706/instance/BkKGAd/ext/fim/static/magick': No such file or directory
```

**Comment by ruanformigoni** [comment]
Hi @fiftydinar , thanks for the bug report! Should  be fixed in `v0.3.1`.
