### ISSUE TITLE
Make executables to strictly contain `.flatimage` extension

### ISSUE THREAD

**Issue by fiftydinar** [ruanformigoni/flatimage#32]
This makes it clearer to the user in which app-format is the application he downloaded.  
Else, there can be confusion when users think that it's the classic static binary or something.

If the executable doesn't contain `.flatimage` extension, warn the user in the logs.

Idk if `.flatimage` or `.FlatImage` naming is preferred, I find both good.
I maybe lean towards `.flatimage` more.

**Comment by ruanformigoni** [comment]
Thanks for the suggestion @fiftydinar! I'll consider adding something like this on the next updates (with an option to silence it the the user wants to). Currently the file type is determined by xdg metadata. In the file manager you should see something like:

![hn](https://github.com/ruanformigoni/flatimage/assets/18180693/55dbaebc-1c04-4645-a490-eff3962633f0)

**Comment by fiftydinar** [comment]
@ruanformigoni Yeah, I see now in Nautilus file properties that it says "FlatImage Application" even when extension is removed.

However, Nautilus doesn't have app type column when using list view, so you have to go to properties to know what is it.
Just a nitpick, not a big deal.

I wouldn't add this option if the user can just disable it tbh.
I suggested this to improve user awareness, but I use grid view in Nautilus, so I didn't notice that you can see this info easily in list view (in Dolphin at least).

So I guess I will close this issue as not planned.
