### ISSUE TITLE
`fim-config-set home` equivalent in new refactored flatimage?

### ISSUE THREAD

**Issue by fiftydinar** [ruanformigoni/flatimage#35]
Before, this command existed:

`./arch.flatimage fim-config-set home '"$FIM_FILE_BINARY".home`

This is really neat for making flatimage even more portable & not cluttering host's `${HOME}` folder.

Is this just undocumented at the moment or the feature is not yet available in refactored flatimage?

Love the overall refactor btw, good job!

**Comment by ruanformigoni** [comment]
Hello @fiftydinar , thanks! That is accomplished with [fim-env](https://flatimage.github.io/docs/cmd/environment/), from the steam example:

```bash
  # Optionally remove access to real HOME (it is disabled by default)
  "$IMAGE" fim-perms del home
  # Configure custom HOME
  "$IMAGE" fim-env add 'USER=steam' \
    'HOME=/home/steam' \
    'XDG_CONFIG_HOME=/home/steam/.config' \
    'XDG_DATA_HOME=/home/steam/.local/share'
```

**Comment by fiftydinar** [comment]
@ruanformigoni I see how it's done now in Steam example, thanks!
