### ISSUE TITLE
Typo in 3-command get of Steam example script

### ISSUE THREAD

**Issue by fiftydinar** [ruanformigoni/flatimage#36]
You wrote this:  
`wget -Osteam.sh https://raw.githubusercontent.com/ruanformigoni/flatimage/refs/heads/master/examples/steam.sh`

While this should be written:  
`wget -O steam.sh https://raw.githubusercontent.com/ruanformigoni/flatimage/refs/heads/master/examples/steam.sh`

**Comment by ruanformigoni** [comment]
Thanks for the heads up, does the first command fail on your side? I haven't found an issue with the version without the extra space.

**Comment by fiftydinar** [comment]
@ruanformigoni Interestingly, it doesn't

I assumed it will fail, but it didn't

**Comment by ruanformigoni** [comment]
I have updated the command for it to be easier to understand. Thanks!
