### ISSUE TITLE
Desktop Integration...

### ISSUE THREAD

**Issue by Heus-Sueh** [ruanformigoni/flatimage#6]
sobre a integração com o desktop aqui vai umas perguntas:

Ele suporta icones tipo o flatpak ou snap?

Ele suporta ser fixado no menu do Gnome ou Plasma?

**Comment by ruanformigoni** [comment]
Olá, comecei a trabalhar no suporte a integração para desktop recentemente, isso faz ser possível a integração com os menus do plasma/gnome. :smile:
