### ISSUE TITLE
Error when trying to run Focal example

### ISSUE THREAD

**Issue by hwittenborn** [ruanformigoni/flatimage#9]
I'm trying to run the Ubuntu 20.04 example, but every time I do I get the following terminal output (on the `./focal.fim fim-root apt install -y firefox` step):

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libdbus-glib-1-2 xul-ext-ubufox
Suggested packages:
  fonts-lyx
The following NEW packages will be installed:
  firefox libdbus-glib-1-2 xul-ext-ubufox
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 61.0 MB of archives.
After this operation, 243 MB of additional disk space will be used.
E: setgroups 65534 failed - setgroups (1: Operation not permitted)
E: setegid 65534 failed - setegid (22: Invalid argument)
E: seteuid 105 failed - seteuid (22: Invalid argument)
E: setgroups 0 failed - setgroups (1: Operation not permitted)
W: chown to _apt:root of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (22: Invalid argument)
W: chown to _apt:root of directory /var/lib/apt/lists/auxfiles failed - SetupAPTPartialDirectory (22: Invalid argument)
E: setgroups 65534 failed - setgroups (1: Operation not permitted)
E: setegid 65534 failed - setegid (22: Invalid argument)
E: seteuid 105 failed - seteuid (22: Invalid argument)
E: setgroups 0 failed - setgroups (1: Operation not permitted)
E: Method gave invalid 400 URI Failure message: Failed to setgroups - setgroups (1: Operation not permitted)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
Terminated
```

Is there something I might be doing wrong, or is this a bug in FlatImage? I'm running in an Ubuntu 20.04 VM if that helps.

By the way, I wanted to say this project looks really cool and I'm hoping to be able to use it in some of my projects! I've tried using AppImages in the past but dependency management was always a hassle. It looks like this project will solve my issues pretty smoothly (I've gotten the Arch and Alpine examples to work great so far), and it looks like it'll be great to distribute my apps to end users!

**Comment by ruanformigoni** [comment]
Hi @hwittenborn , thank you for reporting this issue! This is probably a bug, I'll investigate and get back to you. And thanks again for considering the usage of flatimage in you projects. :)

**Comment by hwittenborn** [comment]
I did some testing @ruanformigoni, and it looks like everything works fine if I run the image with `sudo`:

```
sudo ./focal.fim fim-exec apt install -y firefox
```

I'm not quite sure why `apt` trips up when using `fim-root`, but maybe it should be mentioned in the README that the above method should be used instead for the time being?

**Comment by ruanformigoni** [comment]
I don't recommend using `sudo`, because if the created files are owned by root, that may break the other images that have no superuser access. I think that fakechroot should fix this issue, just as it does in arch, I'll try somethings out and get back to you.

**Comment by ruanformigoni** [comment]
Hi @hwittenborn, I'm currently investigating this issue, but I wasn't able to replicate it. Could it be possible that you had root owned files (by previous sudo executions) ? You can clear the runtime data of `flatimage` with `rm -rf /tmp/fim`. Also, in what environment did run into this issue? I can create a VM to replicate.

**Comment by ruanformigoni** [comment]
I was able to replicate, this is the issue:

https://github.com/ruanformigoni/flatimage/blob/80578e30450158efdeffc7324c7c4f4088049532/src/scripts/_boot.sh#L423

If you edit the file `/tmp/fim/instance/some_instance_number/boot` and comment this out, it'll work. I'll figure out a better way to fix this.

**Comment by hwittenborn** [comment]
I can confirm that fixes the issue @ruanformigoni? What's that needed for (or what does it even do when it's included)?

**Comment by ruanformigoni** [comment]
This got carried over from the default bindings of proot (which was the only option in the earlier versions of this project), and is probably not necessary for bubblewrap, since it currently only supports one user. I'll have to re-test everything to again confirm it however.

**Comment by ruanformigoni** [comment]
Merged the fix into master
